plugins:
  - jekyll-relative-links

# Disable GitHub metadata plugin for local development
github: [metadata]

# Site settings
name: Yorick Brown
title: Full-Stack Developer | Custom WordPress, WooCommerce & API Integrations | Building Scalable, Optimised & Accessible Solutions | JavaScript | PHP | React | OOP
author: Yorick Brown
url: https://yodiyo.github.io
logo: /assets/images/profile.jpg
heading: "🤝 Let's Connect!"
description: "I'm always interested in discussing new opportunities and technical challenges. Feel free to reach out through any of the following channels."
contact1: "https://theyoricktouch.com"
contact2: "mailto:info@theyoricktouch.com"
contact3: "https://linkedin.com/in/theyoricktouch"
contact4: "tel:+447905247756"
nav:
  - title: "Demos"
    url: /demos.html
  - title: "Portfolio"
    url: /portfolio.html

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name

theme: jekyll-theme-minimal
# OR choose from: cayman, slate, tactile, time-machine, leap-day, modernist, architect, dinky, minima
# remote_theme: pages-themes/minimal@v0.2.0
# Popular: mmistakes/minimal-mistakes, just-the-docs/just-the-docs
relative_links:
  enabled: true
  collections: true
include:
  - portfolio.md
  - demos.md
  - README.md
  - index.md

